services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data/pgdata
  webapp:
    image: ghcr.io/shifttreeapp/client:latest
  shifttree:
    image: ghcr.io/shifttreeapp/server:latest
    environment:
      SHIFTTREE_PG_USER: admin
      SHIFTTREE_PG_PASSWORD: "1234"
      SHIFTTREE_PG_HOST: database
      SHIFTTREE_PG_PORT: "5432"
      SHIFTTREE_PG_DATABASE: dev
      SHIFTTREE_JWT_PK: ShiftTree
      SHIFTTREE_PYTHON_HOST: scheduler:8080
  scheduler:
    image: ghcr.io/shifttreeapp/scheduler:latest
    environment:
      SHIFTTREE_SCHEDULING_PORT: 8080
  proxy:
    image: caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80
volumes:
  db_data:
  pgadmin_data:
