# docker compose up -d to start in background
# docker compose down to stop the container

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: "1234"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
  pgadmin_data: